# Generated by Django 2.1.1 on 2018-09-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180918_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='enderecos',
            new_name='endereco',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
